name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "c97183c1a5264f30a28f340664da6cdc" },
  { binding = "SHARE", id = "b679535b30674b28a7a412e64ca4ca25" }
]